package com.alexcaranha.jquerybyhumming.screen.configuration;

import com.alexcaranha.jquerybyhumming.App;
import com.alexcaranha.jquerybyhumming.model.Util;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author alexcaranha
 */
public class Configuration_View extends javax.swing.JPanel implements ActionListener {
    private Configuration_Presenter presenter;

    /**
     * Creates new form SearchSong_View
     */
    public Configuration_View(Configuration_Presenter presenter) throws IOException {
        this.presenter = presenter;

        initComponents();
        initComponentsMannually();
    }

    private void initComponentsMannually() throws IOException {
        this.jButtonBackward.setText("");
        this.jButtonForward.setText("");

        this.jButtonBackward.setIcon(Util.getImageIcon(ImageIO.read(App.getContext().getResource("classpath:figures/backward.png").getInputStream()), 25));
        this.jButtonForward.setIcon(Util.getImageIcon(ImageIO.read(App.getContext().getResource("classpath:figures/forward.png").getInputStream()), 25));
        
        this.jButtonSave.setIcon(Util.getImageIcon(ImageIO.read(App.getContext().getResource("classpath:figures/saveAll.png").getInputStream()), 25));
        this.jButtonLoad.setIcon(Util.getImageIcon(ImageIO.read(App.getContext().getResource("classpath:figures/load.png").getInputStream()), 25));

        this.jButtonBackward.addActionListener(this);
        this.jButtonForward.addActionListener(this);

        this.update();
    }
    
    public void updateTable() {
        this.jLabelConfiguration.setText(presenter.getCurrentConfiguration().getTitle());
        
        this.jPanelConfiguration.removeAll();
        this.jPanelConfiguration.add(presenter.getCurrentConfigurationPanel(), BorderLayout.CENTER);
        
        this.repaint();
        this.revalidate();
    }

    public void update() {
        this.jLabelConfiguration.setText(presenter.getCurrentConfiguration().getTitle());
        this.jButtonBackward.setEnabled(!presenter.indexIsTheFirst());
        this.jButtonForward.setEnabled(!presenter.indexIsTheLast());

        if (presenter.getCurrentConfiguration().isGroup()) {
            this.jLabelOptions.setVisible(true);
            presenter.fillComboOptions(this.jComboBoxOptions);
            this.jComboBoxOptions.setVisible(true);
        } else {
            this.jLabelOptions.setVisible(false);
            this.jComboBoxOptions.setVisible(false);
        }

        this.jPanelConfiguration.removeAll();
        this.jPanelConfiguration.add(presenter.getCurrentConfigurationPanel(), BorderLayout.CENTER);

        this.repaint();
        this.revalidate();
    }
    
    public void actionPerformed(ActionEvent e) {
        Object source = e.getSource();

        if (source == jButtonBackward) {
            presenter.backward();            
        } else
        if (source == jButtonForward) {
            presenter.forward();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelScreens = new javax.swing.JPanel();
        jButtonBackward = new javax.swing.JButton();
        jButtonForward = new javax.swing.JButton();
        jLabelConfiguration = new javax.swing.JLabel();
        jPanelConfiguration = new javax.swing.JPanel();
        jComboBoxOptions = new javax.swing.JComboBox();
        jLabelOptions = new javax.swing.JLabel();
        jButtonSave = new javax.swing.JButton();
        jButtonLoad = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(300, 250));
        setRequestFocusEnabled(false);

        panelScreens.setBackground(new java.awt.Color(227, 234, 242));
        panelScreens.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonBackward.setText("<=");
        jButtonBackward.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBackward.setName("jButtonBackward"); // NOI18N

        jButtonForward.setText("=>");
        jButtonForward.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonForward.setName("jButtonForward"); // NOI18N

        jLabelConfiguration.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelConfiguration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConfiguration.setText("ITEM");
        jLabelConfiguration.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelConfiguration.setOpaque(true);

        jPanelConfiguration.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelConfiguration.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelConfiguration.setLayout(new java.awt.BorderLayout());

        jComboBoxOptions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxOptions.setName("jComboBoxOptions"); // NOI18N
        jComboBoxOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOptionsActionPerformed(evt);
            }
        });

        jLabelOptions.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelOptions.setText("Options");

        jButtonSave.setText("Save");
        jButtonSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonLoad.setText("Load");
        jButtonLoad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelScreensLayout = new javax.swing.GroupLayout(panelScreens);
        panelScreens.setLayout(panelScreensLayout);
        panelScreensLayout.setHorizontalGroup(
            panelScreensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScreensLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelScreensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelConfiguration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelScreensLayout.createSequentialGroup()
                        .addGroup(panelScreensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonBackward, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jLabelOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelScreensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxOptions, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelScreensLayout.createSequentialGroup()
                                .addComponent(jLabelConfiguration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonForward, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelScreensLayout.createSequentialGroup()
                        .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelScreensLayout.setVerticalGroup(
            panelScreensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScreensLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelScreensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelConfiguration, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBackward, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonForward, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelScreensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOptions))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelConfiguration, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelScreensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabelTitle.setBackground(new java.awt.Color(227, 234, 242));
        jLabelTitle.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("CONFIGURATION");
        jLabelTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelTitle.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(panelScreens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelScreens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOptionsActionPerformed
        if (this.jComboBoxOptions.isEditable()) return;
        try {
            this.presenter.setSelected((Configuration)this.jComboBoxOptions.getSelectedItem());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Configuration_View.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Configuration_View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBoxOptionsActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        try {
            this.presenter.save();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Configuration_View.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Configuration_View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadActionPerformed
        try {
            this.presenter.load();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Configuration_View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonLoadActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackward;
    private javax.swing.JButton jButtonForward;
    private javax.swing.JButton jButtonLoad;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox jComboBoxOptions;
    private javax.swing.JLabel jLabelConfiguration;
    private javax.swing.JLabel jLabelOptions;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelConfiguration;
    private javax.swing.JPanel panelScreens;
    // End of variables declaration//GEN-END:variables
}
