package com.alexcaranha.jquerybyhumming.screen.about;

import com.alexcaranha.jquerybyhumming.App;
import com.alexcaranha.jquerybyhumming.model.Util;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author alexcaranha
 */
public final class About_View extends javax.swing.JPanel {

    private About_Presenter presenter;

    public About_View(About_Presenter presenter) throws IOException {
        this.presenter = presenter;

        initComponents();
        initComponentsMannually();
    }

    public void initComponentsMannually() throws IOException {
        this.jLabelImageAuthor.setText("");
        this.jLabelImageLeader.setText("");

        this.jLabelImageAuthor.setIcon(Util.getImageIcon(ImageIO.read(App.getContext().getResource("classpath:figures/AlexLiborioCaranha.png").getInputStream()), 100, 120));
        this.jLabelImageLeader.setIcon(Util.getImageIcon(ImageIO.read(App.getContext().getResource("classpath:figures/LuizWagnerPereiraBiscainho.png").getInputStream()), 100, 120));
        
        About_Model model = (About_Model) presenter.getModel();

        this.jLabelSystem.setText(this.jLabelSystem.getText() + ": " + model.getSystemTitle());
        this.jTextAreaSystem.setText(model.getSystemDescription());

        this.jLabelAuthor.setText(this.jLabelAuthor.getText() + ": " + model.getAuthorTitle());
        this.jTextAreaAuthor.setText(model.getAuthorDescription());

        this.jLabelLeader.setText(this.jLabelLeader.getText() + ": " + model.getLeaderTitle());
        this.jTextAreaLeader.setText(model.getLeaderDescription());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelScreens = new javax.swing.JPanel();
        jLabelImageAuthor = new javax.swing.JLabel();
        jLabelSystem = new javax.swing.JLabel();
        jLabelAuthor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSystem = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaAuthor = new javax.swing.JTextArea();
        jLabelImageLeader = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaLeader = new javax.swing.JTextArea();
        jLabelLeader = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();

        setMaximumSize(null);
        setMinimumSize(null);
        setPreferredSize(null);

        panelScreens.setBackground(new java.awt.Color(227, 234, 242));
        panelScreens.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelImageAuthor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImageAuthor.setText("ImageAuthor");
        jLabelImageAuthor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelSystem.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelSystem.setText("System");
        jLabelSystem.setToolTipText("");

        jLabelAuthor.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelAuthor.setText("Author");
        jLabelAuthor.setToolTipText("");

        jTextAreaSystem.setColumns(20);
        jTextAreaSystem.setRows(5);
        jTextAreaSystem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jTextAreaSystem);

        jTextAreaAuthor.setEditable(false);
        jTextAreaAuthor.setColumns(1);
        jTextAreaAuthor.setLineWrap(true);
        jTextAreaAuthor.setRows(5);
        jTextAreaAuthor.setWrapStyleWord(true);
        jTextAreaAuthor.setAutoscrolls(false);
        jTextAreaAuthor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(jTextAreaAuthor);

        jLabelImageLeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImageLeader.setText("ImageLeader");
        jLabelImageLeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextAreaLeader.setEditable(false);
        jTextAreaLeader.setColumns(1);
        jTextAreaLeader.setLineWrap(true);
        jTextAreaLeader.setRows(5);
        jTextAreaLeader.setWrapStyleWord(true);
        jTextAreaLeader.setAutoscrolls(false);
        jTextAreaLeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane3.setViewportView(jTextAreaLeader);

        jLabelLeader.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelLeader.setText("Leader");
        jLabelLeader.setToolTipText("");

        javax.swing.GroupLayout panelScreensLayout = new javax.swing.GroupLayout(panelScreens);
        panelScreens.setLayout(panelScreensLayout);
        panelScreensLayout.setHorizontalGroup(
            panelScreensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScreensLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelScreensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelScreensLayout.createSequentialGroup()
                        .addComponent(jLabelImageAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelScreensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addComponent(jLabelSystem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(panelScreensLayout.createSequentialGroup()
                        .addComponent(jLabelImageLeader, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelScreensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLeader, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))))
                .addContainerGap())
        );
        panelScreensLayout.setVerticalGroup(
            panelScreensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelScreensLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSystem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelScreensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelImageAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelScreensLayout.createSequentialGroup()
                        .addComponent(jLabelAuthor)
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelScreensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelImageLeader, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelScreensLayout.createSequentialGroup()
                        .addComponent(jLabelLeader)
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabelTitle.setBackground(new java.awt.Color(227, 234, 242));
        jLabelTitle.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("ABOUT");
        jLabelTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelTitle.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelScreens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelScreens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAuthor;
    private javax.swing.JLabel jLabelImageAuthor;
    private javax.swing.JLabel jLabelImageLeader;
    private javax.swing.JLabel jLabelLeader;
    private javax.swing.JLabel jLabelSystem;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaAuthor;
    private javax.swing.JTextArea jTextAreaLeader;
    private javax.swing.JTextArea jTextAreaSystem;
    private javax.swing.JPanel panelScreens;
    // End of variables declaration//GEN-END:variables
}
