package com.alexcaranha.jquerybyhumming.screen.database.detail;

import com.alexcaranha.jquerybyhumming.App;
import com.alexcaranha.jquerybyhumming.components.XYGraphSignal;
import com.alexcaranha.jquerybyhumming.model.Convert;
import com.alexcaranha.jquerybyhumming.model.KeyValue;
import com.alexcaranha.jquerybyhumming.model.Util;
import com.alexcaranha.jquerybyhumming.model.wave.WavFileException;
import com.alexcaranha.jquerybyhumming.view.FilterFileChooser;
import java.awt.BorderLayout;
import java.io.IOException;
import java.util.Map;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JFileChooser;

/**
 *
 * @author alexcaranha
 */
public final class Database_Detail_View extends javax.swing.JPanel implements Observer {

    private Database_Detail_Presenter presenter;

    /**
     * Creates new form Database_Detail_View
     */
    public Database_Detail_View(Database_Detail_Presenter presenter) throws IOException {
        this.setName("DETAIL");
        this.presenter = presenter;

        initComponents();
        initComponentsMannually();
    }

    private void initComponentsMannually() throws IOException {

        this.jButtonPlayStop.setText("Play");
        this.jButtonPlayStop.setIcon(Util.getImageIcon(ImageIO.read(App.getContext().getResource("classpath:figures/play.png").getInputStream()), 25));
        this.jButtonPlayStop.setEnabled(true);

        this.jButtonBack.setIcon(Util.getImageIcon(ImageIO.read(App.getContext().getResource("classpath:figures/back.png").getInputStream()), 25));

        this.fileChooser = new JFileChooser();
        this.fileChooser.addChoosableFileFilter(new FilterFileChooser("MID", "MIDI File"));

        this.jPanelXYGraph = null;
    }

    public void update(Map<String, Object> variables) {
        this.jTextFieldTitle.setText(Convert.toString(variables.get("title")));// presenter.getTitle());
        this.jTextFieldAuthor.setText(Convert.toString(variables.get("author")));
        this.jTextAreaObs.setText(Convert.toString(variables.get("obs")));

        this.jPanelFigure.removeAll();
        this.jPanelXYGraph = new XYGraphSignal("", "time (in seconds)", "MIDI notes", Database_Detail_View.class.getSimpleName(), false);
        this.jPanelFigure.add(jPanelXYGraph, BorderLayout.CENTER);
    }

    public String getTitle() {
        return this.jTextFieldTitle.getText();
    }

    public String getAuthor() {
        return this.jTextFieldAuthor.getText();
    }

    public String getObs() {
        String obs = this.jTextAreaObs.getText();
        return obs == null ? "" : obs;
    }

    public XYGraphSignal getJPanelGraphSignal() {
        return jPanelXYGraph;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPathMidiFile = new javax.swing.JLabel();
        jLabelPathMidiFileValue = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jTextFieldTitle = new javax.swing.JTextField();
        jLabelObs = new javax.swing.JLabel();
        jTextFieldAuthor = new javax.swing.JTextField();
        jButtonBack = new javax.swing.JButton();
        jPanelFigure = new javax.swing.JPanel();
        jLabelAuthor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaObs = new javax.swing.JTextArea();
        jButtonPlayStop = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(390, 285));

        jLabelPathMidiFile.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPathMidiFile.setText("Path MIDI File:");

        jLabelPathMidiFileValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPathMidiFileValue.setText("Click here to open a MIDI file.");
        jLabelPathMidiFileValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelPathMidiFileValue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelPathMidiFileValue.setEnabled(false);

        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTitle.setText("Title:");

        jTextFieldTitle.setEditable(false);
        jTextFieldTitle.setBackground(java.awt.Color.white);
        jTextFieldTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelObs.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelObs.setText("Obs:");

        jTextFieldAuthor.setEditable(false);
        jTextFieldAuthor.setBackground(java.awt.Color.white);
        jTextFieldAuthor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonBack.setText("Back");
        jButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jPanelFigure.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelFigure.setLayout(new java.awt.BorderLayout());

        jLabelAuthor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAuthor.setText("Author:");

        jTextAreaObs.setEditable(false);
        jTextAreaObs.setBackground(java.awt.Color.white);
        jTextAreaObs.setColumns(20);
        jTextAreaObs.setRows(5);
        jTextAreaObs.setText("abc");
        jTextAreaObs.setAutoscrolls(false);
        jTextAreaObs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jTextAreaObs);

        jButtonPlayStop.setText("Play/Stop");
        jButtonPlayStop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPlayStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelObs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelAuthor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAuthor)
                            .addComponent(jTextFieldTitle)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPathMidiFile, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelPathMidiFileValue, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelFigure, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonPlayStop, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPathMidiFileValue)
                    .addComponent(jLabelPathMidiFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFigure, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelObs, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPlayStop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        try {
            this.presenter.back();
        } catch (IOException ex) {
            Logger.getLogger(Database_Detail_View.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Database_Detail_View.class.getName()).log(Level.SEVERE, null, ex);
        } catch (WavFileException ex) {
            Logger.getLogger(Database_Detail_View.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(Database_Detail_View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonPlayStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayStopActionPerformed
        try {
            if (this.jButtonPlayStop.getText().equalsIgnoreCase("Play")) {
                this.presenter.play();
            } else {
                this.presenter.stop();
            }
        } catch (IOException ex) {
            Logger.getLogger(Database_Detail_View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPlayStopActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonPlayStop;
    private javax.swing.JLabel jLabelAuthor;
    private javax.swing.JLabel jLabelObs;
    private javax.swing.JLabel jLabelPathMidiFile;
    private javax.swing.JLabel jLabelPathMidiFileValue;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelFigure;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaObs;
    private javax.swing.JTextField jTextFieldAuthor;
    private javax.swing.JTextField jTextFieldTitle;
    // End of variables declaration//GEN-END:variables
    private XYGraphSignal jPanelXYGraph;
    private JFileChooser fileChooser;

    public void setEnabledPlayStopButton(boolean hasMidiFileInformed) {
        this.jButtonPlayStop.setEnabled(hasMidiFileInformed);
        this.repaint();
        this.revalidate();
    }

    public void updatePlayStopButton(boolean playing) throws IOException {

        if (playing) {
            this.jButtonPlayStop.setText("Stop");
            this.jButtonPlayStop.setIcon(Util.getImageIcon(ImageIO.read(App.getContext().getResource("classpath:figures/stop.png").getInputStream()), 25));
        } else {
            this.jButtonPlayStop.setText("Play");
            this.jButtonPlayStop.setIcon(Util.getImageIcon(ImageIO.read(App.getContext().getResource("classpath:figures/play.png").getInputStream()), 25));
        }

        this.repaint();
        this.revalidate();
    }

    @Override
    public void update(Observable subject, Object argument) {
        //----------------------------------------------------------------------
        if (subject == null) return;
        if (!(argument instanceof KeyValue[])) return;
        //----------------------------------------------------------------------
        KeyValue[] keys = (KeyValue[]) argument;

        /*
         notifyObservers(Util.createArray(new KeyValue("CLASS", null),
                                 new KeyValue("ALIAS", this.alias),
                                 new KeyValue("STATE", "STOP")));
         */

        for(KeyValue keyValue : keys) {
            //System.out.println(String.format("key: %s", keyValue.getKey().toString()));
            if (keyValue.getKey().toString().equalsIgnoreCase("CLASS")) {
                Class classe = (Class) keyValue.getValue();
                if (classe != null) break;
            }
            else if (keyValue.getKey().toString().equalsIgnoreCase("ALIAS")) {
                String aliasArgument = (String) keyValue.getValue();
                if (!aliasArgument.equalsIgnoreCase(Database_Detail_View.class.getSimpleName())) break;
            }
            else if (keyValue.getKey().toString().equalsIgnoreCase("STATE")) {
                boolean enabled = Convert.toBoolean(keyValue.getValue());
                try {
                    updatePlayStopButton(enabled);
                } catch (IOException ex) {
                    Logger.getLogger(Database_Detail_View.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }
}
