package com.alexcaranha.jquerybyhumming.screen.database.search;

import com.alexcaranha.jquerybyhumming.App;
import com.alexcaranha.jquerybyhumming.model.Util;
import com.alexcaranha.jquerybyhumming.screen.database.detail.DatabasePanel;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import org.elasticsearch.action.ActionListener;
import org.elasticsearch.action.search.SearchResponse;

/**
 *
 * @author alexcaranha
 */
public class Database_Search_View extends javax.swing.JPanel implements ActionListener<SearchResponse> {

    private Database_Search_Presenter presenter;

    /**
     * Creates new form Database_Search_View
     */
    public Database_Search_View(Database_Search_Presenter presenter) {
        this.setName("SEARCH");
        this.presenter = presenter;
        initComponents();
        initComponentsMannualy();
    }

    private void initComponentsMannualy() {
        databasePanel = null;
        this.jLabelTitle.setVisible(false);
        this.jTextFieldTitle.setVisible(false);
        this.jButtonSearch.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelData = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jTextFieldTitle = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();

        setMinimumSize(null);

        jPanelData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelData.setLayout(new java.awt.BorderLayout());

        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTitle.setText("Text");

        jButtonSearch.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSearch)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelData, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelData;
    private javax.swing.JTextField jTextFieldTitle;
    // End of variables declaration//GEN-END:variables
    private DatabasePanel databasePanel = null;

    public void onResponse(SearchResponse response) {
        presenter.update(response);
    }

    public void onFailure(Throwable e) {
        String message;
        String buttonsMessage[] = {"Ok"};

        message = e.getMessage();
        if (message.equalsIgnoreCase(String.format("[%s] missing", App.class.getPackage().getName()))) {
            message = "Database is empty.";
        }

        Util.showMessage(message,
                         "Requisition",
                         JOptionPane.YES_OPTION,
                         JOptionPane.QUESTION_MESSAGE, null, buttonsMessage, buttonsMessage[0]);
    }

    public DatabasePanel getPanelData() {
        return databasePanel;
    }

    public void update(DatabasePanel panelData) {
        this.databasePanel = panelData;

        jPanelData.removeAll();
        jPanelData.add(panelData, BorderLayout.CENTER);

        this.repaint();
        this.revalidate();
    }
}
